name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  mediatpy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true
    - run: poetry install --no-interaction --no-root --verbose
    - name: pre-commit
      run: |
        source .venv/bin/activate
        pre-commit install
        pre-commit run --all-files --verbose
      env: |
        SKIP=poetry-lock
    - name: pytest
      run: |
        poetry run pytest --cov --cov-report=lcov:coverage/lcov.info --verbose
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: |      
        poetry build --verbose
    - name: publish
      run: |
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} --skip-existing --verbose
