name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**/README.md'
    - 'docs/**'

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Poetry
      uses: snok/install-poetry@v1  
    - run: poetry install --no-interaction --no-root
    - name: check
      run: |
        poetry check
    - name: lock
      run: |
        poetry lock
    - name: isort
      run: |
        poetry run isort . --check-only --diff
    - name: black
      run: |
        poetry run black . --check
    - name: flake8
      run: |
        poetry run flake8p
    - name: mypy
      run: |
        poetry run mypy .
    - name: bandit
      run: |
        poetry run bandit .
